version: “3.1”

services:
  database:
    container_name: strapi_api
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: password
    volumes:
      - strapi_db:/var/lib/postgresql/data
volumes:
  strapi_db: {}
